import type { Metadata } from "next";
import localFont from "next/font/local";
import { Providers } from "./providers";
import "./globals.scss";
import { Flex } from "@chakra-ui/react";
import { MapComponent } from "@/components/Map";
import { LeftSidebar } from "@/components/LeftSidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Map Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="w-full flex flex-col">
            <Flex
              w="100%"
              justifyContent="space-between"
              alignItems="flex-start"
            >
              <LeftSidebar>{children}</LeftSidebar>
              <MapComponent />
            </Flex>
          </div>
        </Providers>
      </body>
    </html>
  );
}
